### ISSUE TITLE
help command

### ISSUE THREAD

**Issue by Luckygermany** [tibue99/ezcord#50]
### EzCord Version

Master Branch

### Version

Master branch (2.4.1.dev214+gfc7b1042)

### Bug Description

When I ran the help command it was sent normally etc. but I still got this error, I just changed the pycord version from 2.4.1 to the master branch

### Bug Traceback

```
Traceback (most recent call last):
  File "D:\py\lib\site-packages\ezcord\bot.py", line 464, in _error_event
    await error_emb(ctx, error_txt, title=t("error_title", i=ctx))
  File "D:\py\lib\site-packages\ezcord\emb.py", line 258, in error
    return await _process_message(target, embed, txt, title, edit, ephemeral, **kwargs)
  File "D:\py\lib\site-packages\ezcord\emb.py", line 205, in _process_message
    return await _send_embed(target, embed, ephemeral, edit, **kwargs)
  File "D:\py\lib\site-packages\ezcord\emb.py", line 154, in _send_embed
    return await target.response.send_message(
  File "D:\py\lib\site-packages\discord\interactions.py", line 913, in send_message
    await self._locked_response(
  File "D:\py\lib\site-packages\discord\interactions.py", line 1207, in _locked_response
    await coro
  File "D:\py\lib\site-packages\discord\webhook\async_.py", line 222, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.
[ERROR] Error while executing /help 
Traceback (most recent call last):
  File "D:\py\lib\site-packages\discord\commands\core.py", line 131, in wrapped
    ret = await coro(arg)

  File "D:\py\lib\site-packages\discord\commands\core.py", line 1002, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "D:\py\lib\site-packages\ezcord\cogs\help.py", line 205, in help
    await ctx.response.send_message(view=view, embed=embed, ephemeral=self.bot.help.ephemeral)
  File "D:\py\lib\site-packages\discord\interactions.py", line 913, in send_message
    await self._locked_response(
  File "D:\py\lib\site-packages\discord\interactions.py", line 1207, in _locked_response
    await coro
  File "D:\py\lib\site-packages\discord\webhook\async_.py", line 222, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.

```

**Comment by Luckygermany** [comment]
I have install the old version but i still get the same error

**Comment by Luckygermany** [comment]
I dont get this bug now idk whats happend

**Comment by Luckygermany** [comment]
I dont get this bug now idk whats happend
