### ISSUE TITLE
blacklist user used button

### ISSUE THREAD

**Issue by Luckygermany** [tibue99/ezcord#52]
### EzCord Version

Master Branch

### Version

Master branch (2.4.1.dev214+gfc7b1042)

### Bug Description

an user in the blacklist used a button from the bot and the response he is banned to use the bot was correct but i get this error 

### Bug Traceback

```
Traceback (most recent call last):
  File "D:\py\lib\site-packages\discord\ui\view.py", line 422, in _scheduled_task
    allow = await self.interaction_check(interaction)
  File "D:\py\lib\site-packages\ezcord\components.py", line 157, in interaction_check
    if not await coro(interaction):
  File "D:\py\lib\site-packages\ezcord\cogs\blacklist.py", line 45, in view_check
    return await _check_blacklist(interaction)
  File "D:\py\lib\site-packages\ezcord\cogs\blacklist.py", line 39, in _check_blacklist
    raise ErrorMessageSent()
ezcord.errors.ErrorMessageSent
```

**Comment by tibue99** [comment]
Thank you for reporting this bug! I've implemented a fix in #54
